language: go
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"
notificaitons:
  email:
    recipients:
      gomatic@nicerobot.org
    on_success: change
    on_failure: always
install:
  - go get -t ./pkg/... ./cmd/...
script:
  - go test -v ./pkg/... ./cmd/...
